### ISSUE TITLE
When create a proposal, execution period display error

### ISSUE THREAD

**Issue by daojoer** [TomorrowDAOProject/tomorrowDAO-contracts#25]
### Description
When create a proposal, execution period display error

### Steps To Reproduce
1. Log in...
2. Ensure a DAO page
3. Create a Governance proposal, choose voters

### Current Behavior
- Execution period display error
![img_v3_02d4_ab9bcaf5-b7f1-41a2-96f1-4324620575hu](https://github.com/user-attachments/assets/f2016c28-1cf4-4103-a0d0-fba39b9a765e)

### Expected Behavior
- Execution period should display correctly

### Environment
- Platform: PC
- Node: v18.18.0
- Browser: Chrome 126.0.6478.56

**Comment by strongman6693** [comment]
Display errors, non-contractual errors
